### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by MoonDragon-MD** [SkytAsul/NoesisEasyExport#1]
Hi, first of all congratulations on this program, it has made my import work much easier.

I would like it to be added, in the logs or with an alert, when the multiple export process is finished, thanks!

**Comment by SkytAsul** [comment]
Oh wow I would have never guessed someone was using this tool haha
I can add this, sure!

**Comment by MoonDragon-MD** [comment]
> Oh wow I would have never guessed someone was using this tool haha I can add this, sure!

Thank you very kind

**Comment by SkytAsul** [comment]
Voilà :)

**Comment by MoonDragon-MD** [comment]
@SkytAsul Hi, you were very fast to improve it, also graphically, I thank you :)
 but I would have a small improvement: now it's okay for big files to have the end message, but if I have 50 small files it's a problem, so you should put the end message only to the last file in the list to convert, do you think it's possible? 
Sorry for being so nitpicky :P

**Comment by SkytAsul** [comment]
Wait that's what I wanted to do... I placed my code 1 line too high lmao

**Comment by SkytAsul** [comment]
Here you go with 1.0.2

**Comment by MoonDragon-MD** [comment]
> Here you go with 1.0.2

Now it's perfect, thank you very much!!!
